### ISSUE TITLE
Broken PDF images when run in production mode

### ISSUE THREAD

**Issue by aeusebio** [innoveit/play2-pdf#10]
Hi there,

I've been using this module and it have worked wonderfully. But when I run my application in production mode, the PdfGenerator renders the images incorrectly.

Has anyone the same problem?
Have you found any solution?

Thanks in advance.

**Comment by marcosinigaglia** [comment]
I never had problems with images. What kind of problem?

**Comment by aeusebio** [comment]
Sorry, I forgot to attach the print screen.

![screen shot 2016-01-14 at 17 07 21](https://cloud.githubusercontent.com/assets/6757806/12331471/954d3280-bae1-11e5-8917-4e031fecdffe.png)

**Comment by marcosinigaglia** [comment]
The image is inside your project?

**Comment by aeusebio** [comment]
Yes, in 'public\img\logo2.png' and is loaded by '@routes.Assets.at("img/logo2.png")'.

**Comment by marcosinigaglia** [comment]
Can you check with your browser if is correct in production? If you send me the image i'll try to figure it out.

**Comment by aeusebio** [comment]
Yes, in production the web page from which the pdf is generated is rendered correctly.
The logo:
<img width="196" alt="logo2" src="https://cloud.githubusercontent.com/assets/6757806/12332122/afd69a4e-bae4-11e5-8beb-2e7875333571.png">

Btw, I'm using Play!  2.4

**Comment by marcosinigaglia** [comment]
Can you make a test with an another image? It's a strange behavior.

**Comment by aeusebio** [comment]
I've tried other images and the result is similar.

**Comment by marcosinigaglia** [comment]
Do you have a log file? Any errors?

**Comment by aeusebio** [comment]
No errors on the log file.

**Comment by marcosinigaglia** [comment]
Can you check if there are any errors on the webserver production log? Are you using ssh on the server?

**Comment by aeusebio** [comment]
There are no errors.

More info: To package the application I'm using "activator stage", and I start it by running the ".sh" created.

**Comment by aeusebio** [comment]
I kind of resolved the problem by calling a route defined by me instead of the "Assets.at".
That route points to the Application controller in which the image is loaded from disk and returned as a byte array.

It's not a pretty solution but it works...

**Comment by marcosinigaglia** [comment]
Have you tried other play framework version? Maybe is a framework's bug?

**Comment by aeusebio** [comment]
After some testing I discovered that the image was generated with the wrong color information.
After opening the image with an editor and saving it in another format, the problem was solved.

Thanks for all the help.
