### ISSUE TITLE
Does not work with play 2.

### ISSUE THREAD

**Issue by sfakir** [innoveit/play2-pdf#16]
Setup
sbt.version=0.13.11
addSbtPlugin("com.typesafe.play" % "sbt-plugin" % "2.5.0")

libraryDependencies ++= Seq(
  "com.amazonaws" % "aws-java-sdk" % "1.7.1",
  "it.innove" % "play2-pdf" % "1.4.0"
)

"Conflicting cross-version suffixes in ..."

**Comment by marcosinigaglia** [comment]
Hi, have you the same error with play 2.5.4?

**Comment by mgosk** [comment]
Please use version 1.5.0 of play2-pdf
