### ISSUE TITLE
Encoding issue

### ISSUE THREAD

**Issue by cnicodeme** [innoveit/play2-pdf#2]
Hi,

When using : 

`return ok(Html)`

the output contains accent correctly, but when changing it to : 

`return PdfGenerator.ok(Html)`

The generated PDF contains wrongly encoded accents (Ã¨ instead of è)

**Comment by marcosinigaglia** [comment]
Hi, are you using utf-8 charset?

**Comment by cnicodeme** [comment]
Yes :)

**Comment by marcosinigaglia** [comment]
Can you paste your html page?
