### ISSUE TITLE
Problems with encoding.

### ISSUE THREAD

**Issue by vasiliy-komarov** [innoveit/play2-pdf#21]
Hello.
Please look, can you have any ideas what could be the problem.
When generating pdf there is a problem with the symbols.

example:
`<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">`
    `<html>`
        `<head>`
            `@*<meta charset="utf-8"/>*@`
            `<title>Title</title>`
        `</head>`
        `<body>`
            `<div class="pdf-content">`
                `<div class="pdf-label">Label</div>`
                `<div> ТЕКСТ Russian </div>`
            `</div> `   
       `</body>`
    `</html>`

`Html render = template.render();`
`byte[] content = pdfGenerator.toBytes(render, "http://localhost:9001");`

if i use scala template without tag 'meta charset="utf-8', then word 'ТЕКСТ' have wrond encode.
![wrong](https://cloud.githubusercontent.com/assets/7386411/21195452/e51668ca-c244-11e6-8d17-e51c2bd06226.jpg)

if i use scala template with tag 'meta charset="utf-8', then word 'ТЕКСТ' disappear...
![disappear](https://cloud.githubusercontent.com/assets/7386411/21195451/e5124c0e-c244-11e6-854d-5160828c57e8.jpg)

html it turns out right. But pdf wrong.
![html](https://cloud.githubusercontent.com/assets/7386411/21195523/30deb1a4-c245-11e6-874d-d4bb63901e62.jpg)

**Comment by vasiliy-komarov** [comment]
Sorry..
I saw later [issue](https://github.com/innoveit/play2-pdf/issues/14)
but it did not help me.
v. 1.5.1

**Comment by vasiliy-komarov** [comment]
Code now
`<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">`
`<html>`
`    <head>`
`        <meta charset="UTF-8"/>`
`        <link href="https://fonts.googleapis.com/css?family=Open+Sans" rel="stylesheet">`
`        <title>Title</title>`
`    </head>`
`    <body>`
`        <div class="pdf-content">`
`            <div class="pdf-label">Label</div>`
`            <div style="font-family: 'Open Sans';"> ТЕКСТ Russian </div>`
`        </div>`
`    </body>`
`</html>`

` pdfGenerator.loadTemporaryFonts(Arrays.asList(new String[]{"fonts/OpenSans-Regular.ttf"}));`

**Comment by marcosinigaglia** [comment]
Thanks.
