### ISSUE TITLE
Does not output colored font / background.

### ISSUE THREAD

**Issue by playtowork** [innoveit/play2-pdf#22]
Something as simple as the below template does not work. It creates the pdf but the text is black and the background color is still white. Am I missing something, or does this really not support colored font / background?

Specifically, I am doing the following from my Controller:
return ok(pdfGenerator.toBytes(previewStuff.render(),  urlBase)).as("application/pdf");

This is the scala view template file (previewStuff.scala.html):
@()

\<div style='color: blue;'>
  hi there
\</div>
\div style='background-color: red'>
  bye there
\</div>

**Comment by marcosinigaglia** [comment]
Hi, have you tried the example project? The font color and backgroud is supported.
