### ISSUE TITLE
How can I use Messages & Internationalization in a PDF?

### ISSUE THREAD

**Issue by ChickenSniper** [innoveit/play2-pdf#23]
i.e. play.api.i18n.Messages

I need to generate my PDFs based on a user's preferred language.  How would I do this with this package?

**Comment by marcosinigaglia** [comment]
Hi, the Messages works in the same way, if you need to force a language you have to pass as parameter to the template.
`@Messages.get(Lang.forCode(language), "lbl.welcome")`
