### ISSUE TITLE
Change orientation / resolution of generated pdf

### ISSUE THREAD

**Issue by ash-smith** [innoveit/play2-pdf#26]
I was working with this plugin and in HTML, I am using bootstrap's rows and cols, so when I am trying to generate a PDF with that HTML it is not rendered as columns(always in rows style, same when you decrease browser screen side).
So I was thinking is there any way to change the width of PDF or change the orientation to horizontal?
Thanks in advance.

**Comment by marcosinigaglia** [comment]
Hi, I don't think you can use bootstrap so easily, is better if you use fixed dimension, the rendering is not so similar to a modern browser. For the orientation look here: https://github.com/innoveit/play2-pdf/issues/15
