### ISSUE TITLE
Support scala 2.13

### ISSUE THREAD

**Issue by almothafar** [innoveit/play2-pdf#38]
I think you need to publish this lib to work with scala 2.13, as for now, it returns with not found if I tried to use it

**Comment by marcosinigaglia** [comment]
Hi @almothafar , the library is not compiled for a specific scala version so I think is a problem in your build file.

**Comment by almothafar** [comment]
I think this is the reason behind it, because when I do import it like:
```sbt
libraryDependencies ++= Seq(
  ...
      "it.innove" % "play2-pdf" % "1.9.1"
)
```
Which should not be care about the scala version,I get an error:

```console
[error] Modules were resolved with conflicting cross-version suffixes in ProjectRef(uri("file:/Users/almothafar/xxxxx/xxxxx/"), "root"):
[error]    com.typesafe.akka:akka-http-core _2.13, _2.12
[error]    com.typesafe.akka:akka-parsing _2.12, _2.13
[error]    com.typesafe.play:play-functional _2.13, _2.12
[error]    com.typesafe.akka:akka-actor _2.12, _2.13
[error]    com.typesafe.akka:akka-protobuf _2.12, _2.13
[error]    com.typesafe.play:play-streams _2.13, _2.12
[error]    com.typesafe.play:play-json _2.13, _2.12
[error]    com.typesafe.play:play _2.13, _2.12
[error]    org.scala-lang.modules:scala-xml _2.12, _2.13
[error]    com.typesafe.akka:akka-stream _2.12, _2.13
[error]    com.typesafe.play:play-server _2.12, _2.13
[error]    com.typesafe.play:twirl-api _2.13, _2.12
[error]    com.typesafe.play:play-akka-http-server _2.13, _2.12
[error]    com.typesafe.play:play-java _2.12, _2.13
[error]    org.scala-lang.modules:scala-java8-compat _2.13, _2.12
[error]    org.scala-lang.modules:scala-parser-combinators _2.13, _2.12
[error]    com.typesafe:ssl-config-core _2.12, _2.13
[error]    com.typesafe.akka:akka-slf4j _2.13, _2.12
[error]    com.typesafe.play:play-logback _2.12, _2.13
[error]    com.typesafe.play:filters-helpers _2.12, _2.13
[error] stack trace is suppressed; run last update for the full output
[error] stack trace is suppressed; run last ssExtractDependencies for the full output
[error] (update) Conflicting cross-version suffixes in: com.typesafe.akka:akka-http-core, com.typesafe.akka:akka-parsing, com.typesafe.play:play-functional, com.typesafe.akka:akka-actor, com.typesafe.akka:akka-protobuf, com.typesafe.play:play-streams, com.typesafe.play:play-json, com.typesafe.play:play, org.scala-lang.modules:scala-xml, com.typesafe.akka:akka-stream, com.typesafe.play:play-server, com.typesafe.play:twirl-api, com.typesafe.play:play-akka-http-server, com.typesafe.play:play-java, org.scala-lang.modules:scala-java8-compat, org.scala-lang.modules:scala-parser-combinators, com.typesafe:ssl-config-core, com.typesafe.akka:akka-slf4j, com.typesafe.play:play-logback, com.typesafe.play:filters-helpers
[error] (ssExtractDependencies) Conflicting cross-version suffixes in: com.typesafe.akka:akka-http-core, com.typesafe.akka:akka-parsing, com.typesafe.play:play-functional, com.typesafe.akka:akka-actor, com.typesafe.akka:akka-protobuf, com.typesafe.play:play-streams, com.typesafe.play:play-json, com.typesafe.play:play, org.scala-lang.modules:scala-xml, com.typesafe.akka:akka-stream, com.typesafe.play:play-server, com.typesafe.play:twirl-api, com.typesafe.play:play-akka-http-server, com.typesafe.play:play-java, org.scala-lang.modules:scala-java8-compat, org.scala-lang.modules:scala-parser-combinators, com.typesafe:ssl-config-core, com.typesafe.akka:akka-slf4j, com.typesafe.play:play-logback, com.typesafe.play:filters-helpers
[error] Total time: 1 s, completed Nov 18, 2019, 5:51:25 PM)
```

If I try to do (using %% to force 2.13):

```scala
libraryDependencies ++= Seq(
  ...
      "it.innove" %% "play2-pdf" % "1.9.1"
)
```

I get 

```console
[warn] 	Note: Unresolved dependencies path:
[error] stack trace is suppressed; run last update for the full output
[error] stack trace is suppressed; run last ssExtractDependencies for the full output
[error] (update) sbt.librarymanagement.ResolveException: Error downloading it.innove:play2-pdf_2.13:1.9.1
[error]   Not found
[error]   Not found
[error]   not found: /Users/almothafar/.ivy2/local/it.innove/play2-pdf_2.13/1.9.1/ivys/ivy.xml
[error]   not found: https://repo1.maven.org/maven2/it/innove/play2-pdf_2.13/1.9.1/play2-pdf_2.13-1.9.1.pom
[error] (ssExtractDependencies) sbt.librarymanagement.ResolveException: Error downloading it.innove:play2-pdf_2.13:1.9.1
[error]   Not found
[error]   Not found
[error]   not found: /Users/almothafar/.ivy2/local/it.innove/play2-pdf_2.13/1.9.1/ivys/ivy.xml
[error]   not found: https://repo1.maven.org/maven2/it/innove/play2-pdf_2.13/1.9.1/play2-pdf_2.13-1.9.1.pom
[error] Total time: 2 s, completed Nov 18, 2019, 5:53:43 PM)
```

If I remove the module, everything works fine!

For now, What I did is to download the module and imported it locally:

```scala
lazy val playPdf = ProjectRef(file("./play-pdf"), "root")

lazy val root = (project in file("."))
  .dependsOn(playPdf)
  .enablePlugins(PlayJava, PlayEbean, LauncherJarPlugin)
```

This is works for now.

**Comment by almothafar** [comment]
@marcosinigaglia any update on this?

**Comment by hashanchamikara** [comment]
> I think this is the reason behind it, because when I do import it like:
> 
> ```scala
> libraryDependencies ++= Seq(
>   ...
>       "it.innove" % "play2-pdf" % "1.9.1"
> )
> ```
> 
> Which should not be care about the scala version,I get an error:
> 
> ```
> [error] Modules were resolved with conflicting cross-version suffixes in ProjectRef(uri("file:/Users/almothafar/xxxxx/xxxxx/"), "root"):
> [error]    com.typesafe.akka:akka-http-core _2.13, _2.12
> [error]    com.typesafe.akka:akka-parsing _2.12, _2.13
> [error]    com.typesafe.play:play-functional _2.13, _2.12
> [error]    com.typesafe.akka:akka-actor _2.12, _2.13
> [error]    com.typesafe.akka:akka-protobuf _2.12, _2.13
> [error]    com.typesafe.play:play-streams _2.13, _2.12
> [error]    com.typesafe.play:play-json _2.13, _2.12
> [error]    com.typesafe.play:play _2.13, _2.12
> [error]    org.scala-lang.modules:scala-xml _2.12, _2.13
> [error]    com.typesafe.akka:akka-stream _2.12, _2.13
> [error]    com.typesafe.play:play-server _2.12, _2.13
> [error]    com.typesafe.play:twirl-api _2.13, _2.12
> [error]    com.typesafe.play:play-akka-http-server _2.13, _2.12
> [error]    com.typesafe.play:play-java _2.12, _2.13
> [error]    org.scala-lang.modules:scala-java8-compat _2.13, _2.12
> [error]    org.scala-lang.modules:scala-parser-combinators _2.13, _2.12
> [error]    com.typesafe:ssl-config-core _2.12, _2.13
> [error]    com.typesafe.akka:akka-slf4j _2.13, _2.12
> [error]    com.typesafe.play:play-logback _2.12, _2.13
> [error]    com.typesafe.play:filters-helpers _2.12, _2.13
> [error] stack trace is suppressed; run last update for the full output
> [error] stack trace is suppressed; run last ssExtractDependencies for the full output
> [error] (update) Conflicting cross-version suffixes in: com.typesafe.akka:akka-http-core, com.typesafe.akka:akka-parsing, com.typesafe.play:play-functional, com.typesafe.akka:akka-actor, com.typesafe.akka:akka-protobuf, com.typesafe.play:play-streams, com.typesafe.play:play-json, com.typesafe.play:play, org.scala-lang.modules:scala-xml, com.typesafe.akka:akka-stream, com.typesafe.play:play-server, com.typesafe.play:twirl-api, com.typesafe.play:play-akka-http-server, com.typesafe.play:play-java, org.scala-lang.modules:scala-java8-compat, org.scala-lang.modules:scala-parser-combinators, com.typesafe:ssl-config-core, com.typesafe.akka:akka-slf4j, com.typesafe.play:play-logback, com.typesafe.play:filters-helpers
> [error] (ssExtractDependencies) Conflicting cross-version suffixes in: com.typesafe.akka:akka-http-core, com.typesafe.akka:akka-parsing, com.typesafe.play:play-functional, com.typesafe.akka:akka-actor, com.typesafe.akka:akka-protobuf, com.typesafe.play:play-streams, com.typesafe.play:play-json, com.typesafe.play:play, org.scala-lang.modules:scala-xml, com.typesafe.akka:akka-stream, com.typesafe.play:play-server, com.typesafe.play:twirl-api, com.typesafe.play:play-akka-http-server, com.typesafe.play:play-java, org.scala-lang.modules:scala-java8-compat, org.scala-lang.modules:scala-parser-combinators, com.typesafe:ssl-config-core, com.typesafe.akka:akka-slf4j, com.typesafe.play:play-logback, com.typesafe.play:filters-helpers
> [error] Total time: 1 s, completed Nov 18, 2019, 5:51:25 PM)
> ```
> 
> If I try to do (using %% to force 2.13):
> 
> ```scala
> libraryDependencies ++= Seq(
>   ...
>       "it.innove" %% "play2-pdf" % "1.9.1"
> )
> ```
> 
> I get
> 
> ```
> [warn] 	Note: Unresolved dependencies path:
> [error] stack trace is suppressed; run last update for the full output
> [error] stack trace is suppressed; run last ssExtractDependencies for the full output
> [error] (update) sbt.librarymanagement.ResolveException: Error downloading it.innove:play2-pdf_2.13:1.9.1
> [error]   Not found
> [error]   Not found
> [error]   not found: /Users/almothafar/.ivy2/local/it.innove/play2-pdf_2.13/1.9.1/ivys/ivy.xml
> [error]   not found: https://repo1.maven.org/maven2/it/innove/play2-pdf_2.13/1.9.1/play2-pdf_2.13-1.9.1.pom
> [error] (ssExtractDependencies) sbt.librarymanagement.ResolveException: Error downloading it.innove:play2-pdf_2.13:1.9.1
> [error]   Not found
> [error]   Not found
> [error]   not found: /Users/almothafar/.ivy2/local/it.innove/play2-pdf_2.13/1.9.1/ivys/ivy.xml
> [error]   not found: https://repo1.maven.org/maven2/it/innove/play2-pdf_2.13/1.9.1/play2-pdf_2.13-1.9.1.pom
> [error] Total time: 2 s, completed Nov 18, 2019, 5:53:43 PM)
> ```
> 
> If I remove the module, everything works fine!
> 
> For now, What I did is to download the module and imported it locally:
> 
> ```scala
> lazy val playPdf = ProjectRef(file("./play-pdf"), "root")
> 
> lazy val root = (project in file("."))
>   .dependsOn(playPdf)
>   .enablePlugins(PlayJava, PlayEbean, LauncherJarPlugin)
> ```
> 
> This is works for now.

yes I got this problem last week, I create the pull request to resolve this matter

please check this pull #40

**Comment by glarkou** [comment]
Still getting the same issue as described above with scala 2.12.12
