### ISSUE TITLE
UTF-8

### ISSUE THREAD

**Issue by martinscmb** [innoveit/play2-pdf#4]
Hi,
thanks for your commits in this project.

Do you have problems with encoding?
Can you help me to solve it?
Look at my example in this image: 
![capturar](https://cloud.githubusercontent.com/assets/1194272/6374108/a9c77416-bd06-11e4-9c1d-a29d4cf52108.PNG)

The example is not working in caracteres like "ç", "ã","õ"....

Best regards,
Carlos

**Comment by marcosinigaglia** [comment]
Hi Carlos, can you send me you html source?

**Comment by martinscmb** [comment]
Thanks for the quick answer.

Here it is a sample with that problem: https://github.com/martinscmb/PDFExample

Html view source: https://github.com/martinscmb/PDFExample/blob/master/app/views/document.scala.html

**Comment by marcosinigaglia** [comment]
Hi Carlos,
add the meta charset in the page.
`<meta charset="UTF-8">`

**Comment by martinscmb** [comment]
It works!

Thank you so much.

**Comment by martinscmb** [comment]
hi again,

One more question: can you tell me if exists some pdf play 2.x module with FOOTER, HEADER options?

**Comment by marcosinigaglia** [comment]
Hi, this module use Flying Saucer that support header and footer 
http://flyingsaucerproject.github.io/flyingsaucer/r8/guide/users-guide-R8.html#xil_40

**Comment by martinscmb** [comment]
Ty

**Comment by bhaumikkothari** [comment]
hi,
thanks for your commits in this project.
 i want to generate pdf in landscape orientation. How can i do? Please reply soon

**Comment by martinscmb** [comment]
Check this page:
http://flyingsaucerproject.github.io/flyingsaucer/r8/guide/users-guide-R8.html

And use the @page size in your css
