### ISSUE TITLE
Improve project management

### ISSUE THREAD

**Issue by felipebonezi** [innoveit/play2-pdf#44]
Hi 👋🏻 @marcosinigaglia 
Why won't you create a new repository without a fork reference?

We could maintain this project and I would like to help you. 

We could implement the following to improve project management:
- GitHub Actions for CI/CD
- Project labels to easily identify a new issue or PR state
- Release versions using the GitHub's release manager

Little actions could increase help from the community. If you see this repository has a lot of forks and stars.

If you need help, I'm very pleasant to help.

**Comment by marcosinigaglia** [comment]
Hi @felipebonezi , I already made a request to remove the fork reference so is not needed to create a new repo. Your help is very appreciated, do you need mantain permission?

**Comment by felipebonezi** [comment]
@marcosinigaglia sure, give permissions and we could improve the project ASAP :)
