### ISSUE TITLE
"activator run" dont start when adding innoveit pdf module into dependencies

### ISSUE THREAD

**Issue by robert197** [innoveit/play2-pdf#5]
Hello
i was trying to add PDF module into build.sbt 

version := "1.0-SNAPSHOT"

lazy val root = (project in file(".")).enablePlugins(PlayJava)

scalaVersion := "2.11.1"

libraryDependencies ++= Seq(
  jdbc,
  javaEbean,
  cache,
  ws,
  "mysql" % "mysql-connector-java" % "5.1.34",
  "it.innove" % "play2-pdf" % "1.2.0"
  )

when i do it and run the activator i get this. 

[trace] Stack trace suppressed: run last compile:run for the full output.
[error](compile:run) java.lang.NoSuchMethodException: play.core.server.NettyServer.mainDevHttpMode(play.core.BuildLink, play.core.BuildDocHandler, int)
[error] Total time: 8 s, completed 17.06.2015 19:58:34

when  i remove the "it.innove" % "play2-pdf" % "1.2.0" its working again. please i need help!

**Comment by xakernaoffe** [comment]
Have the same issue

**Comment by marcosinigaglia** [comment]
Hi, have you the same issue with the sample project?

**Comment by robert197** [comment]
Hi,
finaly we implemented your addon. we tried an older version and it was
working.
Thank you very much for this great work! i wonder why its working on play
2.4 with but with old version of it.innove but its working...

Thanks!
Robert Pupel

2015-06-24 10:51 GMT+02:00 Marco Sinigaglia notifications@github.com:
