### ISSUE TITLE
Presentation of generated PDF

### ISSUE THREAD

**Issue by bhaumikkothari** [innoveit/play2-pdf#6]
How can i set orientation to landscape for generated pdf?
How can i resize my table in generated pdf?
i.e. all properties for generated pdf ?????

Please reply soon
Thanks

**Comment by martinscmb** [comment]
With this...
http://flyingsaucerproject.github.io/flyingsaucer/r8/guide/users-guide-R8.html#xil_34

**Comment by marcosinigaglia** [comment]
Hi, for orientation use:

``` css
@page {
    size: landscape;
}
```
