### ISSUE TITLE
Ubuntu server encoding issue

### ISSUE THREAD

**Issue by Sean-Sekora** [innoveit/play2-pdf#9]
When I generate a PDF from my laptop everything works well, but when I generate it from an Ubuntu server some of the characters are not encoded correctly.

Laptop generated PDF
https://drive.google.com/open?id=0B2fKdPvkC8IGSno4b3JBR3lKcGs

Ubuntu Server generated PDF
https://drive.google.com/open?id=0B2fKdPvkC8IGaVlxUl8xNHBDd1E

HTML Source
https://drive.google.com/open?id=0B2fKdPvkC8IGaWNOV1ZZMVN5bU0

**Comment by marcosinigaglia** [comment]
Hi, maybe the server change the output charset?
Try replace the $ symbol with `&#36;`
